### PR TITLE
Enhance aoscx_vlan (add voice, vsx_sync, ip_igmp_snooping)

### LINKED ISSUE #46: improvement aoscx_vlan
Hello,

Is it possible to add the following in the `aoscx_vlan` module:
        - vsx-sync
        - ip igmp snooping enable

Thank you :)

### PR DESCRIPTION
**Pull request by alagoutte**
Add 3 news parameters :
- voice (vlan)
- vsx_sync
- ip_igmp_snooping

Fix #46

### CODE REVIEW

**Comment by alagoutte** [comment]
@tchiapuziowong @kchavesr can you review ?

**Comment by tchiapuziowong** [comment]
Hi @alagoutte - thank you for your contribution - this will take us some time to review to ensure functionality across platforms/firmware and no conflicts with our already in progress code - we will update once complete

**Comment by alagoutte** [comment]
@kchavesr can you look ?

**Comment by alagoutte** [comment]
@tchiapuziowong any news about merge this change ?

**Comment by tchiapuziowong** [comment]
> @tchiapuziowong any news about merge this change ?

We included the code provided in this PR in the latest release : https://github.com/aruba/aoscx-ansible-collection/releases/tag/v4.3.0

I'll close this PR

**Comment by alagoutte** [comment]
> > @tchiapuziowong any news about merge this change ?
> 
> We included the code provided in this PR in the latest release : https://github.com/aruba/aoscx-ansible-collection/releases/tag/v4.3.0
> 
> I'll close this PR

Yes, Thanks !

I will update my other change #59 and #62 with new stuff

**Pull request closed without merging**
