### PR TITLE
interfaces(modules_utils): fix  modified-iterating-list

### PR DESCRIPTION
**Pull request by alagoutte**
Iterated list 'vlan_fields' is being modified inside for loop body, consider iterating through a copy of it instead.

### CODE REVIEW

**Comment by alagoutte** [comment]
@tchiapuziowong can you look ?

**Comment by tchiapuziowong** [comment]
@alagoutte removing the for loop isn't the proper solution since that variable is being used in the code- did you validate the modules functioned the same after removing this code?

**Comment by alagoutte** [comment]
> @alagoutte removing the for loop isn't the proper solution since that variable is being used in the code- did you validate the modules functioned the same after removing this code?

look the code, for me it is dead store. There is init the vlan_fields with empty array and after make the for loop with each value of vlan_fields for add a key value of empty vlan_fields

**Comment by tchiapuziowong** [comment]
@alagoutte okay I'll pull and run some sanity tests - thank you for looking into this and the contribution!

**Comment by alagoutte** [comment]
> @alagoutte okay I'll pull and run some sanity tests - thank you for looking into this and the contribution!

it should be nice if there is some integration tests too :)

**Comment by tchiapuziowong** [comment]
Looks good to me! We're working on some code internally that when we're ready to publish we'll include this in the next galaxy version - thanks again!

**Pull request merged**
