### PR TITLE
Add GitHub workflows

### PR DESCRIPTION
**Pull request by alagoutte**
Based on idea/script of @gundalow, Add Github (Actions) workflows

Need to enable Actions if it is not yet enable and fix last issue...

### CODE REVIEW

**Comment by gundalow** [comment]
Doesn't look like GitHub actions are enabled.

**Comment by alagoutte** [comment]
@derekwangHPEAruba @tchiapuziowong it is ready to merge ! can you review (and merge ?)

**Comment by alagoutte** [comment]
> @derekwangHPEAruba @tchiapuziowong it is ready to merge ! can you review (and merge ?)

Some news ?

**Comment by alagoutte** [comment]
any news ?!

**Review by tchiapuziowong — APPROVED** [review]

**Pull request merged**
